version:  '3.7'
services:
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: forecast
      MYSQL_PASSWORD: forecast
      MYSQL_DATABASE: forecast
    volumes:
      - db:/var/lib/mysql
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - app
    volumes:
      - './public:/var/www/app'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8080:80'
  redis:
    image: redis:alpine
    restart: on-failure
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
    - db
    - redis
    restart: on-failure
    volumes:
     - '.:/var/www'
volumes:
  db: